### PR TITLE
fix: support for SDBEGINS and SDBEGINSQ ops, now we correctly decompile wallet v5

### LINKED ISSUE #19: Unknown opcode: b010 when decompile wallet_v5r1 contracts
`Unknown opcode: b010`. Any assistance in resolving this issue or guidance on how to add support for new opcodes would be greatly appreciated. Thank you!

### PR DESCRIPTION
**Pull request by i582**
Fixes #19

### CODE REVIEW

File: src/codepage/opcodes.ts [hunk 1]
```diff
@@ -623,10 +623,17 @@ CP0Auto.insertHex('d723', 16, { code: 'SDSKIPLAST' });
 CP0Auto.insertHex('d724', 16, { code: 'SDSUBSTR' });
 // 14099712 (DUMMY)
 CP0Auto.insertHex('d726', 16, { code: 'SDBEGINSX' });
-CP0Auto.insertHex('d727', 16, { code: 'SDBEGINSXQ' });
```
Comment (Shvandre) [inline src/codepage/opcodes.ts:626]: Where's that opcode gone?

Comment (Shvandre) [reply src/codepage/opcodes.ts:626]: Fixed this

**Comment by Shvandre** [comment]
@anton-trunov  Can you review this, please? Turns out there were problems with the original fix, and I decided to fix them in this same PR. It would be weird if it was reviewed by me)

P.S. Partially closes #34

**Comment by anton-trunov** [comment]
Ok, folks, I have no idea if these fixes are correct. So, let's merge this PR but no more PRs here with features or fixes until we rectify tests. For instance, #33 would be a pretty convincing start.
